import { Printer } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import { formatDate, formatLBP, formatMoney, shortId } from '@/lib/format'

export function Invoice({ open, onClose, documentType, id, placedAt, exchangeRate, partyLabel, partyName, items }) {
  const rows = items.map((item) => ({
    ...item,
    lineTotal: item.quantity * item.unitMultiplier * item.unitPrice,
  }))
  const subtotal = rows.reduce((sum, row) => sum + row.lineTotal, 0)

  return (
    <Modal open={open} onClose={onClose} className="max-w-xl">
      <div className="invoice-print p-8 print:block print:fixed print:inset-0 print:top-0 print:left-0 print:z-[999] print:h-auto print:w-full print:overflow-visible print:bg-white print:p-8 print:text-black print:shadow-none">
        <div className="no-print print:hidden mb-4 flex justify-end">
          <button
            type="button"
            onClick={() => window.print()}
            className="flex items-center gap-1.5 rounded-xl bg-accent-blue px-3 py-1.5 text-[13px] font-semibold text-white hover:opacity-90"
          >
            <Printer size={14} />
            Print / Save PDF
          </button>
        </div>

        <div className="mb-6 flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-blue font-display text-[13px] font-bold text-white">
              IMS
            </div>
            <div>
              <p className="font-display text-[16px] font-semibold text-text-primary">{documentType}</p>
              <p className="text-[12px] text-text-secondary tabular-nums">#{shortId(id)}</p>
            </div>
          </div>
          <div className="text-right text-[12px] text-text-secondary">
            <p>{formatDate(placedAt)}</p>
            <p className="tabular-nums">Rate: {exchangeRate.toLocaleString()} LBP/$</p>
          </div>
        </div>

        <div className="mb-6 rounded-xl border border-hairline p-3">
          <p className="text-[11px] tracking-wide text-text-tertiary uppercase">{partyLabel}</p>
          <p className="text-[14px] font-medium text-text-primary">{partyName ?? `No ${partyLabel.toLowerCase()}`}</p>
        </div>

        <table className="w-full border-collapse text-left text-[13px]">
          <thead>
            <tr className="border-b border-hairline text-[11px] text-text-tertiary">
              <th className="py-2 font-medium">Item</th>
              <th className="py-2 text-right font-medium">Qty</th>
              <th className="py-2 text-right font-medium">Unit</th>
              <th className="py-2 text-right font-medium">Total</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, index) => (
              <tr key={index} className="border-b border-hairline/60">
                <td className="py-2 text-text-primary">{row.name}</td>
                <td className="py-2 text-right text-text-secondary tabular-nums">
                  {row.quantity}
                  {row.unitMultiplier > 1 ? ` × ${row.unitMultiplier}` : ''}
                </td>
                <td className="py-2 text-right text-text-secondary tabular-nums">{formatMoney(row.unitPrice)}</td>
                <td className="py-2 text-right font-medium text-text-primary tabular-nums">
                  {formatMoney(row.lineTotal)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="mt-4 flex flex-col items-end gap-1">
          <div className="flex w-48 justify-between text-[13px]">
            <span className="text-text-secondary">Subtotal</span>
            <span className="font-semibold text-text-primary tabular-nums">{formatMoney(subtotal)}</span>
          </div>
          <div className="flex w-48 justify-between text-[12px]">
            <span className="text-text-secondary">In LBP</span>
            <span className="text-text-secondary tabular-nums">{formatLBP(subtotal, exchangeRate)}</span>
          </div>
        </div>

        <p className="mt-8 text-center text-[11px] text-text-tertiary">Generated by IMS · not a fiscal document</p>
      </div>
    </Modal>
  )
}
