import os
from datetime import timedelta

import dj_database_url
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Initialized as early as possible (before most other settings/imports run), per Sentry's
# own recommendation — but still guarded: with no SENTRY_DSN set (local dev, or before
# it's provisioned in production), this is a no-op rather than an error or dead-weight init.
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # 10% of requests get full performance tracing — a conventional production default,
        # not "sample everything" (expensive/noisy at scale) or "sample nothing" (no signal).
        traces_sample_rate=0.1,
        # Customer/supplier names and phone numbers pass through this app — don't forward
        # request/user PII to Sentry by default (this is also sentry-sdk's own current
        # default, but explicit here so it's not silently toggled on later without review).
        send_default_pii=False,
    )
"""
Django settings for ims project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original hardcoded dev key (unchanged local-dev behavior, harmless
# since it's never exposed anywhere real) when DJANGO_SECRET_KEY isn't set. This key also
# signs JWTs by default (SIMPLE_JWT has no separate SIGNING_KEY) — rotating it on a live
# deployment invalidates every existing session and JWT immediately, forcing every current
# user to log in again. That's a real, disruptive, one-way action: set DJANGO_SECRET_KEY on
# Heroku deliberately, not as an incidental side effect of an unrelated deploy.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-(#!tfz4=kuu1d91rlg+5fqn&x!laf#pa53x=!mg$h&_3&-ffc+'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True (unchanged local-dev behavior) when DJANGO_DEBUG isn't set; Heroku sets
# DJANGO_DEBUG=False explicitly. Accepts '0'/'false'/'no' (case-insensitive) as falsy too,
# not just the literal string 'False', since env vars are always strings.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() not in ('false', '0', 'no')

# Comma-separated list via ALLOWED_HOSTS env var (e.g. "client.myimsapp.com,testlab.myimsapp.com").
# Falls back to '*' (unchanged local-dev/current-prod behavior) when unset. '.myimsapp.com' as a
# leading-dot entry matches that domain and all its subdomains, per Django's ALLOWED_HOSTS docs.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]

# Heroku terminates TLS at its edge and forwards plain HTTP to the dyno — without this,
# SECURE_SSL_REDIRECT (further down, active when DEBUG=False) sees every request as
# insecure and redirects it again, forever. Required for HTTPS detection to work at all
# behind Heroku's router.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

# Multi-tenancy (django-tenants): apps in SHARED_APPS live only in the public schema
# (shared login, admin, tenant registry); apps in TENANT_APPS are migrated into every
# tenant's own PostgreSQL schema, giving each tenant fully isolated data. `inventory`
# is tenant-scoped — that's the actual per-tenant business data (Products, Orders, ...).
# `django.contrib.contenttypes` is listed in both, per django-tenants convention, since
# tenant-schema models may need a local ContentType table.
SHARED_APPS = [
    'django_tenants',  # mandatory, must be first
    'tenants',  # app holding the Tenant/Domain models

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third_party-apps
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'djoser',
    'axes',
    #dev apps
    'playground',
]

# Debug toolbar is a development profiler — it should never be loaded in production, where
# it only adds per-request middleware overhead and an extra exposed URL surface. Its
# middleware short-circuits on DEBUG=False anyway, so gating both here changes nothing
# locally and removes it entirely from the deployed app.
if DEBUG:
    SHARED_APPS.append('debug_toolbar')

TENANT_APPS = [
    'django.contrib.contenttypes',
    #local apps
    'inventory',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = 'tenants.Tenant'
TENANT_DOMAIN_MODEL = 'tenants.Domain'

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)

# Base domain new tenants are provisioned under (see tenants/views.py::TenantOnboardingView),
# i.e. a tenant with schema_name "company" gets domain "company.myimsapp.com". Override via
# env var for other deployments; this app's only real production domain is myimsapp.com.
TENANT_BASE_DOMAIN = os.environ.get('TENANT_BASE_DOMAIN', 'myimsapp.com')

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',  # must run first — sets the DB schema for the request
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(MIDDLEWARE.index('corsheaders.middleware.CorsMiddleware') + 1,
                      'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'ims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ims.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'inventory',
        'HOST': 'localhost',
        'PORT': '5432',
        'USER': 'postgres',
        'PASSWORD': ''
    }
}

# Heroku (and any other DATABASE_URL-based host) sets DATABASE_URL — parse it if present,
# forcing the tenant-aware engine (dj_database_url would otherwise default to plain
# django.db.backends.postgresql, which breaks schema routing entirely). Local dev has no
# DATABASE_URL, so config() returns {} and the DATABASES['default'] block above is unchanged.
_database_url_config = dj_database_url.config(engine='django_tenants.postgresql_backend')
if _database_url_config:
    DATABASES['default'] = _database_url_config

CORS_ALLOW_ALL_ORIGINS = True

# Explicit allowlist, kept alongside the wildcard above for when CORS_ALLOW_ALL_ORIGINS
# is eventually turned off (that flag takes precedence over this list while it's True).
# Covers the Vite dev server both un-tenanted and via the tenant1 subdomain used for
# local multi-tenant testing.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://tenant1.localhost:5173',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING':False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'inventory.permissions.FullDjangoModelPermissions', 
    )
}


SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Only affects /admin/ — the React app authenticates via JWT (see SIMPLE_JWT above), not
# Django sessions. Kept here for admin-site hardening per security review.
SESSION_COOKIE_AGE = 2592000  # 30 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
# Heroku's router sits in front of every request as a single reverse proxy, so without this,
# axes (via django-ipware) reads REMOTE_ADDR — Heroku's internal, per-request router-hop
# address (10.x.x.x), not the real client IP. That makes the ['username', 'ip_address']
# lockout bucket above nearly meaningless: unrelated failed logins from different real users
# can land in the same bucket (since the "IP" it sees rotates independently of who's actually
# connecting), locking out legitimate users for other people's failed attempts. Trusting
# exactly one proxy hop and reading X-Forwarded-For recovers the real client IP.
AXES_IPWARE_PROXY_COUNT = 1
AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
# Only makes the header eligible for HSTS preload submission — does NOT submit the domain
# anywhere itself. Actually submitting to hstspreload.org is a separate, much harder to
# reverse decision (can take months to be removed from browsers afterward) left to you.
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Serves the built React app's JS/CSS at the root-relative paths Vite already emits
# them at (e.g. /assets/index-XXXX.js), separately from STATIC_URL-prefixed Django
# static files (admin CSS, etc.) — see ims/views.py::spa_index for index.html itself.
WHITENOISE_ROOT = BASE_DIR / 'frontend' / 'dist'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Namespaces every uploaded file (e.g. ProductImage) under media/<tenant_schema_name>/...
# instead of a single shared media/ tree, so tenants can never see each other's uploads —
# matching the schema-level isolation `inventory` already has. "%s" is where django-tenants
# inserts the active tenant's schema_name (see django_tenants.utils.parse_tenant_config_path).
MULTITENANT_RELATIVE_MEDIA_ROOT = '%s'

STORAGES = {
    'default': {
        'BACKEND': 'django_tenants.files.storage.TenantFileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Cloudflare R2 / AWS S3 (both speak the S3 API — set AWS_S3_ENDPOINT_URL for R2, leave
# unset for real AWS S3) for production media, still namespaced per tenant — see
# ims.storage.TenantS3Storage. Sourced entirely from env vars: nothing here is a real
# credential. Only takes effect when AWS_STORAGE_BUCKET_NAME is actually set (Heroku config
# vars); local dev has none of these set, so STORAGES['default'] above is left as-is.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')  # set for R2; omit for AWS S3
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')  # R2 has no real regions
AWS_S3_ADDRESSING_STYLE = 'virtual'
# R2's own *.r2.cloudflarestorage.com endpoint requires a signed Authorization header on
# every request, including GETs — it's an API endpoint, not a public CDN, so browsers can't
# load images from it directly. AWS_S3_CUSTOM_DOMAIN (a domain connected to the bucket via
# Cloudflare's "Custom Domains" or the r2.dev public bucket URL) makes django-storages build
# URLs against that instead. Left unset, URLs fall back to the private API endpoint above.
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')
AWS_DEFAULT_ACL = None  # R2 doesn't support canned ACLs the way S3 does
AWS_QUERYSTRING_AUTH = False  # serve plain URLs, not presigned ones

if AWS_STORAGE_BUCKET_NAME:
    STORAGES['default']['BACKEND'] = 'ims.storage.TenantS3Storage'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25  # Matches the smtp4dev container port mapping
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'ims-system@local.test'