# Generated by Django 6.0.8 on 2026-08-08 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-()]{6,32}$', 'Enter a phone number — digits, spaces, dashes and an optional leading +.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly subscription'), ('one_time', 'One-time licence (lifetime)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription_status',
            field=models.CharField(choices=[('pending_verification', 'Pending email verification'), ('pending_payment', 'Pending payment'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], db_index=True, default='pending_verification', max_length=32),
        ),
    ]
