# Generated by Django 6.0.8 on 2026-08-08 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auth_user_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField(default=100)),
                ('grants', models.CharField(choices=[('months', 'A number of months'), ('lifetime', 'Lifetime licence')], default='lifetime', max_length=16)),
                ('grant_months', models.PositiveSmallIntegerField(blank=True, help_text='Required when the key grants months.', null=True)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kill switch.')),
                ('amount_paid_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountKeyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_redemptions', to='accounts.account')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounts.discountkey')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('key', 'account'), name='uniq_discount_key_per_account')],
            },
        ),
    ]
