# Generated by Django 6.0.8 on 2026-08-12 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_discountkey_discountkeyredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='paddle_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='paddle_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly subscription'), ('annual', 'Annual subscription'), ('one_time', 'One-time licence (lifetime)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription_status',
            field=models.CharField(choices=[('pending_verification', 'Pending email verification'), ('pending_payment', 'Pending payment'), ('trialing', 'Free trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], db_index=True, default='pending_verification', max_length=32),
        ),
    ]
