# Generated by Django 6.0.8 on 2026-08-10 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_discountkey_discountkeyredemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset')], db_index=True, default='email_verification', max_length=32),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='emailverif_user_purpose_idx'),
        ),
    ]
