# Generated by Django 6.0.8 on 2026-08-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverification_purpose'),
        ('accounts', '0006_processedwebhookevent_account_paddle_customer_id_and_more'),
    ]

    operations = [
    ]
