# Generated by Django 6.0.8 on 2026-08-12 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260812_1242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Set the first time a trial starts. Blocks a second free trial.'),
        ),
        migrations.CreateModel(
            name='UserPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('whish', 'Whish Money'), ('omt', 'OMT'), ('card', 'Card (via Paddle)'), ('other', 'Other')], default='cash', max_length=16)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('encrypted_details', models.BinaryField(blank=True, default=b'')),
                ('reference', models.CharField(blank=True, default='', help_text='Non-sensitive lookup handle, e.g. a receipt number. Stored in the clear.', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='accounts.account')),
                ('user', models.ForeignKey(blank=True, help_text='Who recorded this, when it was entered by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='payrec_account_created_idx')],
            },
        ),
    ]
