# Generated by Django 6.0.8 on 2026-08-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='registration_expires_at',
            field=models.DateTimeField(blank=True, help_text='Deadline for an unverified sign-up. Cleared on verification; a NULL value means this account is not a pending registration.', null=True),
        ),
    ]
