# Generated by Django 6.0.8 on 2026-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_registration_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_dual_currency',
            field=models.BooleanField(default=True, help_text='Show secondary-currency equivalents alongside the primary currency.'),
        ),
        migrations.AddField(
            model_name='account',
            name='primary_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('LBP', 'Lebanese Pound')], default='USD', help_text='Display currency for inventory figures. Does not affect stored amounts or billing.', max_length=3),
        ),
    ]
