# Generated by Django 6.0.8 on 2026-08-09 09:33

import django.core.validators
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_unit_cost_price(apps, schema_editor):
    """
    Stamp existing lines with their product's cost as it stands today.

    This is an approximation and the best one available — the true cost at the time of each
    historical sale was never recorded and cannot be recovered. Every order placed after
    this migration is exact. A Subquery rather than F('product__cost_price') because
    update() refuses to follow a join.
    """
    OrderItem = apps.get_model('inventory', 'OrderItem')
    Product = apps.get_model('inventory', 'Product')
    OrderItem.objects.filter(unit_cost_price__isnull=True).update(
        unit_cost_price=Subquery(
            Product.objects.filter(pk=OuterRef('product_id')).values('cost_price')[:1]
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        # Three steps in one file. Adding the column non-null in a single shot would fail on
        # any existing row, and adding it with a default of 0 would record a 100% margin for
        # every order ever placed.
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_price',
            field=models.DecimalField(
                max_digits=9, decimal_places=2, null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(backfill_unit_cost_price, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost_price',
            field=models.DecimalField(
                max_digits=9, decimal_places=2,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
