# Generated by Django 6.0.8 on 2026-08-09 10:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_discountkey_discountkeyredemption'),
        ('inventory', '0002_orderitem_unit_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries'), ('marketing', 'Marketing'), ('software', 'Software'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('taxes_fees', 'Taxes & Fees'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('spent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.account')),
            ],
            options={
                'ordering': ['-spent_at'],
                'indexes': [models.Index(fields=['account', '-spent_at'], name='expense_account_date_idx')],
            },
        ),
    ]
