# Generated by Django 6.0.7 on 2026-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.IntegerField(default=89000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.IntegerField(default=89000),
        ),
    ]
