# Generated by Django 6.0.7 on 2026-08-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.IntegerField(blank=True, default=89000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.IntegerField(blank=True, default=89000),
        ),
    ]
