# Generated by Django 6.0.8 on 2026-08-10 08:48

from django.db import migrations, models
from django.db.models import Count, Min


def clear_duplicate_barcodes(apps, schema_editor):
    """
    Free the constraint to be added: within each account, the *earliest* product keeps a
    shared code and the rest are cleared to NULL.

    Phase 4 permitted duplicates, so rows predating this migration may hold them. NULL is the
    honest resolution — a shared code means the database does not know which product it
    identifies, and inventing a suffix would fabricate a barcode that matches no physical
    label. Cleared products are named on stdout so the owner can rescan them; the field is
    optional, so nothing else breaks in the meantime.
    """
    Product = apps.get_model('inventory', 'Product')

    duplicated = (
        Product.objects
        .exclude(barcode__isnull=True)
        .values('account_id', 'barcode')
        .annotate(rows=Count('id'), keeper=Min('id'))
        .filter(rows__gt=1)
    )

    cleared = []
    for group in duplicated:
        losers = Product.objects.filter(
            account_id=group['account_id'], barcode=group['barcode'],
        ).exclude(id=group['keeper'])
        cleared.extend(losers.values_list('name', 'barcode'))
        losers.update(barcode=None)

    if cleared:
        print(
            f'\n  Cleared {len(cleared)} duplicate barcode(s) so each code identifies one '
            f'product. Rescan these:'
        )
        for name, barcode in cleared:
            print(f'    {barcode}  {name}')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_discountkey_discountkeyredemption'),
        ('inventory', '0004_product_barcode'),
    ]

    operations = [
        # Clear first, then constrain. Adding the constraint against existing duplicate rows
        # fails the migration outright and leaves the deployment half-applied.
        migrations.RunPython(clear_duplicate_barcodes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(
                fields=('account', 'barcode'), name='uniq_product_account_barcode',
            ),
        ),
    ]
