# Generated by Django 6.0.8 on 2026-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_order_paid_amount_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
