# Generated by Django 6.0.7 on 2026-08-03 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_orderitem_unit_price_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost of a single unit, independent of stock_quantity.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_sell_price',
            field=models.DecimalField(decimal_places=2, help_text='Sell price of a single unit, independent of stock_quantity.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
