# Generated by Django 6.0.8 on 2026-08-05 20:40

import inventory.fields
import inventory.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=inventory.fields.ExternalOrLocalImageField(upload_to='inventory/images', validators=[inventory.validators.validate_file_size]),
        ),
    ]
