/**
 * Invoice branding.
 *
 * The seller's name, phone and email are *account* data — `business_name`, `phone` and
 * `email` on the subscription payload — and are read from there at render time, not from
 * here. These constants are only the fallback for an account that has not filled them in,
 * so an invoice never prints a blank letterhead.
 *
 * Deliberately no logo and no seller address: the reference layout has neither, and both
 * would need per-account storage this app does not have.
 */
export const INVOICE_FALLBACK_NAME = 'Your business'
export const INVOICE_FALLBACK_EMAIL = ''
export const INVOICE_FALLBACK_PHONE = ''

/** Printed under the totals. Edit for your own sign-off. */
export const INVOICE_TAGLINE = 'Thank you for your business!'

/**
 * The small print below the tagline. Kept honest: this app does not register invoices with
 * any tax authority, and saying so on the document is cheaper than explaining it later.
 */
export const INVOICE_FOOTER_NOTE = 'Generated by IMS — not a fiscal document'
